@ShirtsShop.Api_HostAddress = https://localhost:7021

GET {{ShirtsShop.Api_HostAddress}}/shirts

###

POST {{ShirtsShop.Api_HostAddress}}/shirts

###

GET {{ShirtsShop.Api_HostAddress}}/shirts/1

###

PUT {{ShirtsShop.Api_HostAddress}}/shirts/1

###

DELETE {{ShirtsShop.Api_HostAddress}}/shirts/1

###
